// Supabase Auth "Send Email" hook.
//
// Auth calls this instead of its own SMTP sender, handing over the six digit
// code it has already generated and recorded. We work out which of the three
// apps the reader belongs to, render that app's email, and hand it to Resend.
// Auth still owns generation, expiry and verification — this function only
// decides what the email looks like.
//
// Required secrets (never hardcode, never commit):
//   RESEND_API_KEY         - from resend.com/api-keys
//   SEND_EMAIL_HOOK_SECRET - shown when the hook is created, `v1,whsec_...`
//   OTP_FROM_ADDRESS       - bare address on a domain verified in Resend
//
//   supabase secrets set RESEND_API_KEY=re_... \
//     SEND_EMAIL_HOOK_SECRET=v1,whsec_... \
//     OTP_FROM_ADDRESS=no-reply@mysetu.live
//
// Optional:
//   OTP_FROM         - a full From header that overrides per-brand naming
//   BRAND_ASSET_BASE - where the logos live; defaults to the project's own
//                      public `brand` storage bucket
//
// SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are injected by the platform.

import { Webhook } from "https://esm.sh/standardwebhooks@1.0.0";

import {
  type Brand,
  brandForRole,
  brandFromRedirect,
  DEFAULT_BRAND,
} from "./brands.ts";
import { render } from "./template.ts";

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
const HOOK_SECRET = Deno.env.get("SEND_EMAIL_HOOK_SECRET");
const FROM_ADDRESS = Deno.env.get("OTP_FROM_ADDRESS") ?? "no-reply@mysetu.live";
const FROM_OVERRIDE = Deno.env.get("OTP_FROM");

const SUPABASE_URL = Deno.env.get("SUPABASE_URL") ?? "";
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const ASSET_BASE = Deno.env.get("BRAND_ASSET_BASE") ??
  `${SUPABASE_URL}/storage/v1/object/public/brand`;

interface HookPayload {
  user: { email: string };
  email_data: {
    token: string;
    email_action_type: string;
    redirect_to?: string;
  };
}

/// The logo is remote because inline attachments are unreliable across
/// clients, and a 1254px brand PNG is not something to put in an inbox. The
/// bucket holds the 128px discs generated by core/build_email_logos.py.
function logoUrl(brand: Brand): string {
  return `${ASSET_BASE}/${brand.key}.png`;
}

/// Looks the address up in the role tables. Returns null on any failure — a
/// slow or broken lookup must cost the reader a logo, never a login, so the
/// caller falls through to the default brand rather than failing the send.
async function roleForEmail(email: string): Promise<string | null> {
  if (!SUPABASE_URL || !SERVICE_ROLE_KEY) return null;
  try {
    const res = await fetch(
      `${SUPABASE_URL}/rest/v1/rpc/setu_role_for_email`,
      {
        method: "POST",
        headers: {
          apikey: SERVICE_ROLE_KEY,
          Authorization: `Bearer ${SERVICE_ROLE_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ p_email: email }),
        signal: AbortSignal.timeout(3000),
      },
    );
    if (!res.ok) {
      console.error(`send-email: role lookup returned ${res.status}`);
      return null;
    }
    const role = await res.json();
    return typeof role === "string" ? role : null;
  } catch (error) {
    console.error("send-email: role lookup failed", error);
    return null;
  }
}

/// An app may force a brand through its redirect URL; otherwise the address
/// decides. The address is the better answer in the one case where the two
/// disagree — an ASHA verifying a mother's address sends from the ASHA app to
/// the mother's inbox — so the override exists for future apps, not for that.
async function resolveBrand(payload: HookPayload): Promise<Brand> {
  const explicit = brandFromRedirect(payload.email_data.redirect_to);
  if (explicit) return explicit;

  const role = await roleForEmail(payload.user.email);
  return brandForRole(role) ?? DEFAULT_BRAND;
}

/// Kannada in a From header renders as boxes wherever the font is missing,
/// and the inbox list is the one place the reader cannot tap to fix it — so
/// the Latin name is what goes here, not brand.name.
function fromHeader(brand: Brand): string {
  return FROM_OVERRIDE ?? `${brand.nameLatin} <${FROM_ADDRESS}>`;
}

Deno.serve(async (req) => {
  if (req.method !== "POST") {
    return new Response("Method not allowed", { status: 405 });
  }
  if (!RESEND_API_KEY || !HOOK_SECRET) {
    console.error("send-email: RESEND_API_KEY or SEND_EMAIL_HOOK_SECRET unset");
    return new Response(
      JSON.stringify({ error: { http_code: 500, message: "Mailer not configured" } }),
      { status: 500, headers: { "Content-Type": "application/json" } },
    );
  }

  const raw = await req.text();
  let payload: HookPayload;

  // Anyone can reach a deployed function URL. Only Auth can sign the body, so
  // an unverified request never reaches Resend and never burns quota.
  try {
    const headers = Object.fromEntries(req.headers);
    const wh = new Webhook(HOOK_SECRET.replace("v1,whsec_", ""));
    payload = wh.verify(raw, headers) as HookPayload;
  } catch (error) {
    console.error("send-email: signature rejected", error);
    return new Response(
      JSON.stringify({ error: { http_code: 401, message: "Invalid signature" } }),
      { status: 401, headers: { "Content-Type": "application/json" } },
    );
  }

  const brand = await resolveBrand(payload);
  // The brand key is safe to log; the address and the code are not.
  console.log(`send-email: sending as ${brand.key}`);

  const { subject, html, text } = render(
    brand,
    payload.email_data.token,
    logoUrl(brand),
  );

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${RESEND_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from: fromHeader(brand),
      to: [payload.user.email],
      subject,
      html,
      text,
    }),
  });

  if (!res.ok) {
    // Never log the body of a failure that might echo the code back.
    console.error(`send-email: resend returned ${res.status}`);
    return new Response(
      JSON.stringify({ error: { http_code: 502, message: "Could not send the code" } }),
      { status: 502, headers: { "Content-Type": "application/json" } },
    );
  }

  return new Response("{}", {
    status: 200,
    headers: { "Content-Type": "application/json" },
  });
});
