#!/usr/bin/env bash
# Build the two SQL files that stand a fresh Supabase project up from nothing.
#
#   ./core/bootstrap_new_project.sh
#   -> build/bootstrap_1_schema.sql   paste into the SQL editor, Run
#   -> build/bootstrap_2_data.sql     paste into the SQL editor, Run
#
# Why a build step rather than a list of files to paste in order: the order is
# the whole difficulty. Columns are added by one file and inserted into by
# another four files later, so a single wrong position fails halfway and leaves
# a half-built database that looks fine until a screen comes back empty. This
# encodes the order once, and each file stays the single authority on its own
# part of the schema.
#
# Everything here is idempotent - create table if not exists, add column if not
# exists, create or replace. Re-running is safe, and is the way to apply a
# change to a project that already exists.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/build"
mkdir -p "$OUT"

# Order is load-bearing. The notes say what each step makes possible; do not
# reorder without following the column through to whoever inserts into it.
SCHEMA=(
  # Base tables: health_centres, asha_workers, mothers, checkups, weight/bp
  # entries, tt_doses, baby_vaccines, baby_growth, schemes.
  "thayi/supabase/migrations/0001_init.sql"

  # The platform contract on top of the mother app's own tables - staff,
  # anc_visits, tasks, alerts, referrals, clinical_notes, labs, and the
  # mothers columns all three apps share. Also staff.email, which four of the
  # files below depend on.
  "core/schema.sql"

  # mothers.home_lat/home_lng/home_note/home_located_at.
  "core/mother_home_location.sql"

  # These three run in this order and no other. email_verification.sql adds
  # email_verified, which the gate function in mother_email_gate.sql reads -
  # and a `language sql` function is parsed when it is created, so a missing
  # column fails there and then rather than on first call.
  # mothers.email itself is in schema.sql above, because otherwise these two
  # files each need a column the other creates.
  "core/email_verification.sql"
  # The sign-in gate and the auth.users link trigger.
  "core/mother_email_gate.sql"
  # Redefines the gate to require verification. Must follow mother_email_gate.
  "core/email_verification_gate.sql"

  # Ties a staff row to its login on first sign-in. Needs staff.email.
  "core/link_staff_trigger.sql"
  # asha_workers latitude/longitude and the unauthenticated directory a woman
  # who has not registered yet can still read.
  "core/public_asha_directory.sql"
  # access_grants, plus the triggers that refuse an address already used by
  # the other side. Needs both mothers.email and staff.email.
  "core/access_grants.sql"
  # prescriptions table, its storage bucket and policies. Needs
  # can_access_mother from schema.sql.
  "core/prescriptions.sql"

  # What Ask Setu is allowed to answer from.
  "core/pregnancy_faqs.sql"
  "core/pregnancy_faqs_seed.sql"
  "core/pregnancy_faqs_papaya.sql"

  # Which app's logo the OTP email wears. Needs staff.email and mothers.email.
  "core/brand_for_email.sql"
)

# Separate file because it is 220KB and because it is the one part you will
# re-run on its own - it clears the demo caseload and lays it down again.
DATA=(
  "core/demo_dataset.sql"
)

emit() {
  local target="$1"; shift
  : > "$target"
  {
    echo "-- GENERATED by core/bootstrap_new_project.sh - do not edit."
    echo "-- Edit the source files listed below and re-run the script."
    echo "--"
    echo "-- Built $(date -u '+%Y-%m-%d %H:%M UTC')"
    echo
  } >> "$target"

  for f in "$@"; do
    [[ -f "$ROOT/$f" ]] || { echo "missing $f" >&2; exit 1; }
    {
      echo
      echo "-- ==================================================================="
      echo "-- $f"
      echo "-- ==================================================================="
      echo
      cat "$ROOT/$f"
      echo
    } >> "$target"
  done
  echo "$(basename "$target")  $(wc -l < "$target" | tr -d ' ') lines, $(( $(wc -c < "$target") / 1024 ))KB"
}

emit "$OUT/bootstrap_1_schema.sql" "${SCHEMA[@]}"
emit "$OUT/bootstrap_2_data.sql"   "${DATA[@]}"

cat <<'NEXT'

Next, in the SQL editor of the NEW project:
  1. paste build/bootstrap_1_schema.sql  -> Run
  2. paste build/bootstrap_2_data.sql    -> Run

Step 2 ends in a check that raises if any signed-in account was left unlinked,
so "Success" there means the data really is wired to the logins.

  pbcopy < build/bootstrap_1_schema.sql
NEXT
